### ISSUE TITLE
Wiki: 快速上手 存在的一点 typos

### ISSUE THREAD

**Issue by imWildCat** [Gh0u1L5/WechatSpellbook#12]
1. `if (isImportantWechatProcess(lpparam))` -> `if (isImportantWechatProcess(lpparam))`，最后一个括号为全角

2. `Operation<Long?>` -> `Operation<Long>`

3. `if (Spellbook.isImportantWechatProcess(lpparam)） {` -> `if (SpellBook.isImportantWechatProcess(lpparam)） {`，`book` 应改为 `Book`

**Comment by Gh0u1L5** [comment]
感谢反馈，问题已修复。
