### ISSUE TITLE
[Feature]后续能否支持Magisk框架呢

### ISSUE THREAD

**Issue by amnextking** [Gh0u1L5/WechatSpellbook#2]
本人手机为一加5，之前一直想折腾Xposed框架，但由于要解锁BL一直未尝试。
在接触到VirtualXposed之后开始尝试，不巧那时候微信巫师在上面运行不是很完善。
索性解BL刷上了Magisk，后续又安装了Systemless版的Xposed，开始了愉快地搞机。
Magisk安上之后手机一切正常，但由于模块太少。又安装上Xposed，但安装之后工商银行及静读天下无法正常运行，偶尔卡卡的，不知是何原因，大神若是知道有劳解释一下。

本人对搞机很有兴趣，后续准备写些模块解决日常需求。个人感觉Magisk在7.1上表现相对较好，我想请教开发过Xposed模块的大神们，将Xposed模块移植至Magisk工程量如何呢？
在这里希望此框架后续可以支持Magisk框架，十分感谢。

**Comment by Gh0u1L5** [comment]
Ummm，Magisk是一个systemless的框架，你可以用它来安全的修改系统文件，但是不能用它修改运行中的应用，所以它跟Xposed模块之间没有什么关系，也不能跟Xposed框架互换。
