### ISSUE TITLE
使用快速上手教程，无法启动微信

### ISSUE THREAD

**Issue by ginhoor** [Gh0u1L5/WechatSpellbook#23]
我的微信版本是6.7.3，实际那个Alert的Toast是可以弹出来的，但是马上微信就会crash，应该是被微信检测出来了吧，请问我有办法绕过检测么

**Comment by ginhoor** [comment]
更新一下问题，我出现问题是因为用了手动集成的方式，后来用Maven引入，就不会出现这个问题了

**Comment by ldwonday** [comment]
@ginhoor 用那个不会导致微信无法打开？Storage吗？
