### ISSUE TITLE
[feature]有无可能开发收发消息的接口？

### ISSUE THREAD

**Issue by frankiezdh** [Gh0u1L5/WechatSpellbook#3]

**Comment by koko01024122** [comment]
可以搞

**Comment by zhangnew** [comment]
收消息的话，拦截数据库操作就行了。发消息有点困难，正在研究。

**Comment by Blankeer** [comment]
https://github.com/Blankeer/WechatBotXposed 已实现回复功能

**Comment by frankiezdh** [comment]
@Blankeer 非常感谢。

**Comment by xinGCN** [comment]
> 收消息的话，拦截数据库操作就行了。发消息有点困难，正在研究。

收消息的时候，拦截数据库虽然能够很容易获取到文本。但是图片和文件如何获取比较好呢，求赐教～
