### ISSUE TITLE
7.0.0 init问题

### ISSUE THREAD

**Issue by fyt1399** [Gh0u1L5/WechatSpellbook#36]
WechatSpellbook在7.0.0以上的微信版本中parse apk会失败，原因是因为7.0.0的apk大小有90+MB，2s的初始化时间不足以把整个类树给parse出来。如果有需求7.0.0以上版本的同学可以自行把源码里的初始化限制放宽。

**Comment by zy990081568** [comment]
7.0.3没问题 而且很快

**Comment by fyt1399** [comment]
> 7.0.3没问题 而且很快

可能和使用环境也有关。我这里使用的是VirtualXposed+红米6，运行的速度会降低很多。方便的话能把您的使用环境说一下吗？

**Comment by zy990081568** [comment]
魅蓝5s 直接刷的Xposed框架运行的
