### ISSUE TITLE
我觉得却少了一样东西，打赏二维码

### ISSUE THREAD

**Issue by pengMaster** [Gh0u1L5/WechatSpellbook#5]

**Comment by DanteAndroid** [comment]
人家在乎你那点捐赠？

**Comment by JessYanCoding** [comment]
打赏的意义在于认可, 至于多少是个人的心意

**Comment by Gh0u1L5** [comment]
惊了，大家评论区戾气不要这么重啊……

**Comment by DanteAndroid** [comment]
@JessYanCoding 打赏的意义我不否认，可是作者文章里明确写出了自己的价值观，他却还发这个issue，我是不是可以认为没有认真读文章呢？

**Comment by Gh0u1L5** [comment]
嘛，我把打赏码发了不就不会再有人发issue问了吗，大家和气一点和气一点。

**Comment by Xavier-i** [comment]
哟小伙，很受欢迎嘛

**Comment by pengMaster** [comment]
对不起在座各位，看到好的东西有感而发，是我失态了，再次道歉，对不起各位
